### ISSUE TITLE
Circuit Sword not booting-up

### ISSUE THREAD

**Issue by nokmaar** [kiteretro/Circuit-Sword#101]
Hello!

I have a circuit sword from a few years ago I never powered up. Now that we've got all this free time (covid-19) I'm finally putting some time in.

I powered it with the USB-C and I'm using an SD card with a good retropie image that I'm using on a free standing Pi-0 and screen.

However, when I start the unit up I get a white screen, a few blinks of "act" and not much else.
I've re-seated the SD card and the CM3 a few times with no change.
Any ideas what I can do?
Based on other conversations I see on here it seems the CM3 isn't booting since there is an led off that you mention often.

![CS Issue](https://user-images.githubusercontent.com/63519112/79054390-59702a00-7c12-11ea-8f1e-3079fd422a46.jpg)

**Comment by kiteretro** [comment]
Hi, so the issue is that nothing is being loaded from the SD card. This could either be the SD isn't properly imaged or that there is a bad connection on the board. Assuming you have used the correct image from this site, and imaged it to an SD card such that when you insert the SD into your PC it shows as a 58MB drive with a number of files on, with one of them being `config-cs.txt`, then you have imaged it right and it is the SD slot..

Right now I am not accepting returns and not able to ship anything out, however when the global situation calms down a little such that I am able to, I would be happy to repair for you. If you are confident at soldering, the issue is that the SD slot itself is not fully soldered. If you remove the SD you can see the SD slot legs through the inspection holes. One or more of them isn't properly soldered! It is possible with the iron going in the SD slot edge and feeding solder into the inspection holes to rework them, however it's not that easy so I would advise caution..

Perhaps best would be to send me an email to kite@kiteretro.com and when things go a little more back to normal I'll be able to sort it out for you.
