### ISSUE TITLE
[Next] Safe shutdown should cleanly exit Emulation Station

### ISSUE THREAD

**Issue by c-hri-s** [kiteretro/Circuit-Sword#19]
Hi,

The safe shutdown (when you use the power button) doesn't seem to cleanly exit ES.

I have ES configured to write metadata on exit, yet it doesn't save favourites or last played unless I explicitly exit ES from the menus before shutting the GBZ down.

Is there a way to have the safe shutdown exit ES and allow it to save metadata before powering off?

**Comment by kiteretro** [comment]
This link looks related: https://retropie.org.uk/forum/topic/12895/ensuring-es-gracefully-finish-and-save-metadata-in-every-system-shutdown

It looks simple enough for me to implemented. In short it registers a service that when a shutdown is called it is run very early on in the process so that it safely kills ES (rather than a harder kill signal)
