### ISSUE TITLE
Charging indicator even if powerd off

### ISSUE THREAD

**Issue by Adim01** [kiteretro/Circuit-Sword#20]
Would love to see a charing indicator onscreen while the board is pluged to the wall to see how much juice it got (like on a smartphone).

**Comment by kiteretro** [comment]
On screen isn't possible, the Pi is the only thing on the board that can drive the screen therefore to see the level the Pi needs to be on and running.. the CHRG status LED is there for this reason, so it's possible to see if it is currently charging or complete.

Beware about the battery bar while charging.. the bar is driven by the battery voltage ONLY and NOT the capacity (for example your phone tracks the capacity and how much is left, the implementation here does not and makes some assumptions (E.g. >4v = 100% and <3.3v = 0%). The way batteries charge means that it will be at 4.2V for a long time before it is 'charged' .. hence why there are the icons and the external CHRG LED.. so even if the screen showed you the bar, it would not show you the actual charge percentage! :)

In order to do what you want, would require special chips and calibrated parameters.. phones are good at this because they OEM the batteries and are all calibrated.. this is why typically 3rd party batteries can sometimes just 'drop' because they have not been calibrated properly.

Hope that makes sense! Closing this issue as it cannot be done on this PCB.
