### ISSUE TITLE
Overscan problem on 640x480 display

### ISSUE THREAD

**Issue by Joe2824** [kiteretro/Circuit-Sword#98]
If I change the overscan left or right the display starts to flicker. 
Overscan top and bottom have no issues.

I'm using the newest board with the new 640x480 display.

**Comment by bin101** [comment]
I am facing the same issue but at my side I get the flickering also if I set top/bottom overscan.

**Comment by kiteretro** [comment]
Hi why are you trying to use overscan? Does anything get cut off in normal use?

**Comment by bin101** [comment]
For my part I wanted to cut off some pixel on the bottom because my glass lens printing is covering some space of the display. But now I think overscan is the wrong approach for this.

**Comment by kiteretro** [comment]
Overscan isn't very good for this need because it will compress the image making the whole thing blurry, it doesn't reduce the visible screen area (e.g. if you set overscan bottom as 20px, it will still output 640x480 into a 'window' at 640x460, BUT the overscan doesn't scale quite like that, it usually ends up doing a linear scale so it will narrow the sides too..). You may have better luck editing the HDMI settings line, which is the long one that you have to uncomment to get the LCD to work, and adjust the '480' value lower, that MIGHT work but it will likely not.. the best solution is to make the visible area visible.. or you can adjust these things per app better in the SELECT + Y menu thing and set the scaling and offset per app instead

**Comment by Joe2824** [comment]
The tipp with the HDMI settings does not work.
The boot looks not nice because the text is hidden from display glass.
Also the battery and wifi icons are hidden.
Is it possible to change the location of these icons? 

![img](https://user-images.githubusercontent.com/4028085/72662922-f2651f80-39ec-11ea-83ca-cf4986008d87.jpg)

**Comment by kiteretro** [comment]
Currently there isn't a way, i'll have a look to see if I can find some settings that may help

**Comment by kiteretro** [comment]
Closing as this will be fixed as part of #67
